name: musi_chat
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  flutter_statusbarcolor: ^0.2.3
  font_awesome_flutter: ^9.1.0
  rive: ^0.7.28
  bubble: ^1.2.1
  syncfusion_flutter_sliders: ^19.3.44
  socket_io_client: ^1.0.1
  line_icons: ^2.0.1
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: ^0.9.2
  rename: ^1.3.1
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/musiChatLogo.png"

flutter_native_splash:
  
  android: true
  ios: true
  web: true

  color: "#303841"
  image: assets/musiChatIconG.png

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - riveAssets/music_wave_dark.riv
    - riveAssets/music_wave_light.riv
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/comfortaa.ttf
